baseURL = 'https://emanuelhentes.com'
languageCode = 'en-us'
title = 'Emanuel Hentes'
theme = 'PaperMod'

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"

[params.profileMode]
enabled = true
title = ''
subtitle = '''PhD Candidate┃Utrecht University 

‎ 

e.hentes@uu.nl'''
imageUrl = 'photo.jpg'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/emanuelhentes/'

[[params.socialIcons]]
name = 'twitter'
url = 'https://www.twitter.com/emanuelhentes/'

[[params.socialIcons]]
name = 'googlescholar'
url = 'https://scholar.google.com/citations?hl=en&user=eBsRTXUAAAAJ'

[[params.socialIcons]]
name = 'orcid'
url = 'https://orcid.org/0000-0003-4909-6974'

[[params.socialIcons]]
name = 'researchgate'
url = 'https://www.researchgate.net/profile/Emanuel-Hentes-2'

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
[[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 30
[[menus.main]]
    name = 'CV'
    pageRef = '/cv'
    weight = 30



